/* Generated by scripts/gen_params.py — DO NOT EDIT BY HAND.
 *
 * module.json is capped at 8 KB by Schwung's loader, so chain_params and the
 * page hierarchy are served dynamically from the DSP via get_param().
 *
 * The pot and enum tables below define storage order for the state blob.
 * Appending is safe; reordering breaks every saved patch.
 */
#ifndef SC808_PARAMS_H
#define SC808_PARAMS_H

typedef enum { SC808_LIN = 0, SC808_EXP = 1 } sc808_curve_t;

typedef struct {
    const char    *key;
    float          min;
    float          max;
    sc808_curve_t  curve;
    int            def;      /* default POT position, 0..127 */
} sc808_pot_t;

typedef struct {
    const char *key;
    int         count;      /* number of options */
    int         def;
} sc808_enum_t;

#define SC808_NUM_POTS  71
#define SC808_NUM_ENUMS 19

static const sc808_pot_t g_sc808_pots[SC808_NUM_POTS] = {
    { "bd_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "bd_attack",     0.0000f,     1.0000f, SC808_LIN,  24 },
    { "bd_decay",     0.1000f,     8.0000f, SC808_EXP,  87 },
    { "bd_tone",     0.0000f,     6.0000f, SC808_LIN,  42 },
    { "bd_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "bd_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "sd_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "sd_decay",     0.1000f,     8.0000f, SC808_EXP, 108 },
    { "sd_snappy",     0.0000f,     1.0000f, SC808_LIN,  89 },
    { "sd_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "sd_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "lt_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "lt_decay",     0.0600f,     2.0000f, SC808_EXP,  68 },
    { "lt_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "lt_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "mt_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "mt_decay",     0.0600f,     2.0000f, SC808_EXP,  56 },
    { "mt_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "mt_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ht_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "ht_decay",     0.0600f,     2.0000f, SC808_EXP,  53 },
    { "ht_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ht_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "lc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "lc_decay",     0.0600f,     2.0000f, SC808_EXP,  58 },
    { "lc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "lc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "mc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "mc_decay",     0.0600f,     2.0000f, SC808_EXP,  36 },
    { "mc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "mc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "hc_tune",    -2.0000f,     2.0000f, SC808_LIN,  64 },
    { "hc_decay",     0.0600f,     2.0000f, SC808_EXP,  34 },
    { "hc_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "hc_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "rs_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "rs_decay",     0.0050f,     0.2000f, SC808_EXP,  40 },
    { "rs_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "rs_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cl_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "cl_decay",     0.0000f,     1.0000f, SC808_LIN,  64 },
    { "cl_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cl_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ma_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "ma_attack",     0.0000f,     0.1000f, SC808_LIN,  34 },
    { "ma_decay",     0.0100f,     0.3000f, SC808_EXP,  51 },
    { "ma_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ma_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cp_tune",   -12.0000f,    12.0000f, SC808_LIN,  64 },
    { "cp_decay",     0.3500f,     2.8000f, SC808_EXP,  64 },
    { "cp_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cp_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cb_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "cb_decay",     0.1000f,     2.0000f, SC808_EXP,  62 },
    { "cb_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cb_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "ch_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "ch_decay",     0.0300f,     0.5000f, SC808_EXP,  47 },
    { "ch_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "ch_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "oh_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "oh_decay",     0.0800f,     1.5000f, SC808_EXP,  74 },
    { "oh_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "oh_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "cy_tune",     0.5000f,     2.0000f, SC808_EXP,  64 },
    { "cy_decay",     0.4000f,     6.0000f, SC808_EXP,  70 },
    { "cy_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "cy_level",     0.0000f,     2.0000f, SC808_LIN,  64 },
    { "master_drive",     0.0000f,    10.0000f, SC808_LIN,   0 },
    { "volume",     0.0000f,     1.0000f, SC808_LIN, 100 },
    { "accent",     1.0000f,     4.0000f, SC808_LIN,  42 },
};

static const sc808_enum_t g_sc808_enums[SC808_NUM_ENUMS] = {
    { "bd_dist_type",  4,  0 },
    { "sd_dist_type",  4,  0 },
    { "lt_dist_type",  4,  0 },
    { "mt_dist_type",  4,  0 },
    { "ht_dist_type",  4,  0 },
    { "lc_dist_type",  4,  0 },
    { "mc_dist_type",  4,  0 },
    { "hc_dist_type",  4,  0 },
    { "rs_dist_type",  4,  0 },
    { "cl_dist_type",  4,  0 },
    { "ma_dist_type",  4,  0 },
    { "cp_dist_type",  4,  0 },
    { "cb_dist_type",  4,  0 },
    { "ch_dist_type",  4,  0 },
    { "hh_choke",  3,  1 },
    { "oh_dist_type",  4,  0 },
    { "cy_dist_type",  4,  0 },
    { "master_dist",  5,  0 },
    { "note_map",  2,  0 },
};

#define SC808_CHAIN_PARAMS_LEN 8138
static const char sc808_chain_params_json[] =
    "[{\"key\":\"bd_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"bd_attack\",\"nam"
    "e\":\"Attack\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":24,\"viz\":false},{\"key\":\"bd_decay\",\"name\":\"Decay"
    "\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":87},{\"key\":\"bd_tone\",\"name\":\"Tone\",\"type\":\"int\",\"min\":0,\""
    "max\":127,\"default\":42},{\"key\":\"bd_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},"
    "{\"key\":\"bd_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"d"
    "efault\":0},{\"key\":\"bd_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind"
    "\":\"fader\"}},{\"key\":\"sd_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"sd_d"
    "ecay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":108},{\"key\":\"sd_snappy\",\"name\":\"Snappy"
    "\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":89},{\"key\":\"sd_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0"
    ",\"max\":127,\"default\":0},{\"key\":\"sd_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\""
    "Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"sd_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lt_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"d"
    "efault\":64},{\"key\":\"lt_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":68},{\"key\":\"lt"
    "_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"lt_dist_type\",\"name\":\"Dis"
    "tortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"lt_level\",\"nam"
    "e\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"mt_tune\",\"nam"
    "e\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"mt_decay\",\"name\":\"Decay\",\"type\":\"int\""
    ",\"min\":0,\"max\":127,\"default\":56},{\"key\":\"mt_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"de"
    "fault\":0},{\"key\":\"mt_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\""
    "Crush\"],\"default\":0},{\"key\":\"mt_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"v"
    "iz\":{\"kind\":\"fader\"}},{\"key\":\"ht_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\""
    "key\":\"ht_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":53},{\"key\":\"ht_drive\",\"name\""
    ":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"ht_dist_type\",\"name\":\"Distortion\",\"type"
    "\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ht_level\",\"name\":\"Level\",\"ty"
    "pe\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"lc_tune\",\"name\":\"Tune\",\"typ"
    "e\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"lc_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":58},{\"key\":\"lc_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"ke"
    "y\":\"lc_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"defau"
    "lt\":0},{\"key\":\"lc_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"f"
    "ader\"}},{\"key\":\"mc_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"mc_decay"
    "\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":36},{\"key\":\"mc_drive\",\"name\":\"Drive\",\"type"
    "\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"mc_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"opti"
    "ons\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"mc_level\",\"name\":\"Level\",\"type\":\"int\",\"min"
    "\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"hc_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\""
    ":0,\"max\":127,\"default\":64},{\"key\":\"hc_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\""
    ":34},{\"key\":\"hc_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"hc_dist_ty"
    "pe\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":"
    "\"hc_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\""
    ":\"rs_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"rs_decay\",\"name\":\"Deca"
    "y\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":40},{\"key\":\"rs_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":"
    "0,\"max\":127,\"default\":0},{\"key\":\"rs_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\","
    "\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"rs_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,"
    "\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cl_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\""
    "default\":64},{\"key\":\"cl_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"c"
    "l_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cl_dist_type\",\"name\":\"Di"
    "stortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cl_level\",\"na"
    "me\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ma_tune\",\"na"
    "me\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ma_attack\",\"name\":\"Attack\",\"type\":\"i"
    "nt\",\"min\":0,\"max\":127,\"default\":34},{\"key\":\"ma_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,"
    "\"default\":51},{\"key\":\"ma_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"m"
    "a_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0"
    "},{\"key\":\"ma_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\""
    "}},{\"key\":\"cp_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cp_decay\",\"na"
    "me\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cp_drive\",\"name\":\"Drive\",\"type\":\"in"
    "t\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cp_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":"
    "[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cp_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\""
    "max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cb_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"m"
    "ax\":127,\"default\":64},{\"key\":\"cb_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":62},"
    "{\"key\":\"cb_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"cb_dist_type\",\""
    "name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"cb_l"
    "evel\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"ch_"
    "tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"ch_decay\",\"name\":\"Decay\",\"t"
    "ype\":\"int\",\"min\":0,\"max\":127,\"default\":47},{\"key\":\"ch_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"ma"
    "x\":127,\"default\":0},{\"key\":\"ch_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip"
    "\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"ch_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"defa"
    "ult\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"hh_choke\",\"name\":\"Choke\",\"type\":\"enum\",\"options\":[\"Off\",\"CH>"
    "OH\",\"Mutual\"],\"default\":1},{\"key\":\"oh_tune\",\"name\":\"Tune\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":6"
    "4},{\"key\":\"oh_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":74},{\"key\":\"oh_drive\",\""
    "name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0},{\"key\":\"oh_dist_type\",\"name\":\"Distortion\","
    "\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"oh_level\",\"name\":\"Level"
    "\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kind\":\"fader\"}},{\"key\":\"cy_tune\",\"name\":\"Tune\""
    ",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64},{\"key\":\"cy_decay\",\"name\":\"Decay\",\"type\":\"int\",\"min\":0,"
    "\"max\":127,\"default\":70},{\"key\":\"cy_drive\",\"name\":\"Drive\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":0}"
    ",{\"key\":\"cy_dist_type\",\"name\":\"Distortion\",\"type\":\"enum\",\"options\":[\"Diode\",\"Clip\",\"Fold\",\"Crush\"],\""
    "default\":0},{\"key\":\"cy_level\",\"name\":\"Level\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":64,\"viz\":{\"kin"
    "d\":\"fader\"}},{\"key\":\"master_dist\",\"name\":\"Master Dist\",\"type\":\"enum\",\"options\":[\"Off\",\"Diode\",\"Clip\""
    ",\"Fold\",\"Crush\"],\"default\":0},{\"key\":\"master_drive\",\"name\":\"Master Drive\",\"type\":\"int\",\"min\":0,\"max\""
    ":127,\"default\":0},{\"key\":\"volume\",\"name\":\"Volume\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":100,\"viz\""
    ":{\"kind\":\"fader\"}},{\"key\":\"accent\",\"name\":\"Accent\",\"type\":\"int\",\"min\":0,\"max\":127,\"default\":42},{\"ke"
    "y\":\"note_map\",\"name\":\"Note Map\",\"type\":\"enum\",\"options\":[\"Rack 36\",\"GM\"],\"default\":0},{\"key\":\"ui_foc"
    "us\",\"name\":\"Focus\",\"type\":\"int\",\"min\":0,\"max\":16,\"default\":0},{\"key\":\"mutes\",\"name\":\"Mutes\",\"type\":\""
    "int\",\"min\":0,\"max\":65535,\"default\":0}]";

#define SC808_UI_PAGES_LEN 5584
static const char sc808_ui_pages_json[] =
    "{\"levels\":{\"bd\":{\"name\":\"Bass Drum\",\"knobs\":[\"bd_tune\",\"bd_attack\",\"bd_decay\",\"bd_tone\",\"bd_drive\",\""
    "bd_dist_type\",\"bd_level\"],\"params\":[{\"key\":\"bd_tune\",\"name\":\"Tune\"},{\"key\":\"bd_attack\",\"name\":\"Attac"
    "k\"},{\"key\":\"bd_decay\",\"name\":\"Decay\"},{\"key\":\"bd_tone\",\"name\":\"Tone\"},{\"key\":\"bd_drive\",\"name\":\"Driv"
    "e\"},{\"key\":\"bd_dist_type\",\"name\":\"Distortion\"},{\"key\":\"bd_level\",\"name\":\"Level\"}]},\"sd\":{\"name\":\"Sna"
    "re\",\"knobs\":[\"sd_tune\",\"sd_decay\",\"sd_snappy\",\"sd_drive\",\"sd_dist_type\",\"sd_level\"],\"params\":[{\"key\""
    ":\"sd_tune\",\"name\":\"Tune\"},{\"key\":\"sd_decay\",\"name\":\"Decay\"},{\"key\":\"sd_snappy\",\"name\":\"Snappy\"},{\"ke"
    "y\":\"sd_drive\",\"name\":\"Drive\"},{\"key\":\"sd_dist_type\",\"name\":\"Distortion\"},{\"key\":\"sd_level\",\"name\":\"L"
    "evel\"}]},\"lt\":{\"name\":\"Low Tom\",\"knobs\":[\"lt_tune\",\"lt_decay\",\"lt_drive\",\"lt_dist_type\",\"lt_level\"],"
    "\"params\":[{\"key\":\"lt_tune\",\"name\":\"Tune\"},{\"key\":\"lt_decay\",\"name\":\"Decay\"},{\"key\":\"lt_drive\",\"name\""
    ":\"Drive\"},{\"key\":\"lt_dist_type\",\"name\":\"Distortion\"},{\"key\":\"lt_level\",\"name\":\"Level\"}]},\"mt\":{\"name"
    "\":\"Mid Tom\",\"knobs\":[\"mt_tune\",\"mt_decay\",\"mt_drive\",\"mt_dist_type\",\"mt_level\"],\"params\":[{\"key\":\"mt"
    "_tune\",\"name\":\"Tune\"},{\"key\":\"mt_decay\",\"name\":\"Decay\"},{\"key\":\"mt_drive\",\"name\":\"Drive\"},{\"key\":\"mt"
    "_dist_type\",\"name\":\"Distortion\"},{\"key\":\"mt_level\",\"name\":\"Level\"}]},\"ht\":{\"name\":\"Hi Tom\",\"knobs\":["
    "\"ht_tune\",\"ht_decay\",\"ht_drive\",\"ht_dist_type\",\"ht_level\"],\"params\":[{\"key\":\"ht_tune\",\"name\":\"Tune\"}"
    ",{\"key\":\"ht_decay\",\"name\":\"Decay\"},{\"key\":\"ht_drive\",\"name\":\"Drive\"},{\"key\":\"ht_dist_type\",\"name\":\"D"
    "istortion\"},{\"key\":\"ht_level\",\"name\":\"Level\"}]},\"lc\":{\"name\":\"Low Conga\",\"knobs\":[\"lc_tune\",\"lc_deca"
    "y\",\"lc_drive\",\"lc_dist_type\",\"lc_level\"],\"params\":[{\"key\":\"lc_tune\",\"name\":\"Tune\"},{\"key\":\"lc_decay\""
    ",\"name\":\"Decay\"},{\"key\":\"lc_drive\",\"name\":\"Drive\"},{\"key\":\"lc_dist_type\",\"name\":\"Distortion\"},{\"key\""
    ":\"lc_level\",\"name\":\"Level\"}]},\"mc\":{\"name\":\"Mid Conga\",\"knobs\":[\"mc_tune\",\"mc_decay\",\"mc_drive\",\"mc_"
    "dist_type\",\"mc_level\"],\"params\":[{\"key\":\"mc_tune\",\"name\":\"Tune\"},{\"key\":\"mc_decay\",\"name\":\"Decay\"},{"
    "\"key\":\"mc_drive\",\"name\":\"Drive\"},{\"key\":\"mc_dist_type\",\"name\":\"Distortion\"},{\"key\":\"mc_level\",\"name\""
    ":\"Level\"}]},\"hc\":{\"name\":\"Hi Conga\",\"knobs\":[\"hc_tune\",\"hc_decay\",\"hc_drive\",\"hc_dist_type\",\"hc_leve"
    "l\"],\"params\":[{\"key\":\"hc_tune\",\"name\":\"Tune\"},{\"key\":\"hc_decay\",\"name\":\"Decay\"},{\"key\":\"hc_drive\",\"n"
    "ame\":\"Drive\"},{\"key\":\"hc_dist_type\",\"name\":\"Distortion\"},{\"key\":\"hc_level\",\"name\":\"Level\"}]},\"rs\":{\""
    "name\":\"Rim Shot\",\"knobs\":[\"rs_tune\",\"rs_decay\",\"rs_drive\",\"rs_dist_type\",\"rs_level\"],\"params\":[{\"key"
    "\":\"rs_tune\",\"name\":\"Tune\"},{\"key\":\"rs_decay\",\"name\":\"Decay\"},{\"key\":\"rs_drive\",\"name\":\"Drive\"},{\"key"
    "\":\"rs_dist_type\",\"name\":\"Distortion\"},{\"key\":\"rs_level\",\"name\":\"Level\"}]},\"cl\":{\"name\":\"Claves\",\"kno"
    "bs\":[\"cl_tune\",\"cl_decay\",\"cl_drive\",\"cl_dist_type\",\"cl_level\"],\"params\":[{\"key\":\"cl_tune\",\"name\":\"T"
    "une\"},{\"key\":\"cl_decay\",\"name\":\"Decay\"},{\"key\":\"cl_drive\",\"name\":\"Drive\"},{\"key\":\"cl_dist_type\",\"nam"
    "e\":\"Distortion\"},{\"key\":\"cl_level\",\"name\":\"Level\"}]},\"ma\":{\"name\":\"Maracas\",\"knobs\":[\"ma_tune\",\"ma_a"
    "ttack\",\"ma_decay\",\"ma_drive\",\"ma_dist_type\",\"ma_level\"],\"params\":[{\"key\":\"ma_tune\",\"name\":\"Tune\"},{\""
    "key\":\"ma_attack\",\"name\":\"Attack\"},{\"key\":\"ma_decay\",\"name\":\"Decay\"},{\"key\":\"ma_drive\",\"name\":\"Drive\""
    "},{\"key\":\"ma_dist_type\",\"name\":\"Distortion\"},{\"key\":\"ma_level\",\"name\":\"Level\"}]},\"cp\":{\"name\":\"Hand "
    "Clap\",\"knobs\":[\"cp_tune\",\"cp_decay\",\"cp_drive\",\"cp_dist_type\",\"cp_level\"],\"params\":[{\"key\":\"cp_tune\""
    ",\"name\":\"Tune\"},{\"key\":\"cp_decay\",\"name\":\"Decay\"},{\"key\":\"cp_drive\",\"name\":\"Drive\"},{\"key\":\"cp_dist_"
    "type\",\"name\":\"Distortion\"},{\"key\":\"cp_level\",\"name\":\"Level\"}]},\"cb\":{\"name\":\"Cowbell\",\"knobs\":[\"cb_t"
    "une\",\"cb_decay\",\"cb_drive\",\"cb_dist_type\",\"cb_level\"],\"params\":[{\"key\":\"cb_tune\",\"name\":\"Tune\"},{\"ke"
    "y\":\"cb_decay\",\"name\":\"Decay\"},{\"key\":\"cb_drive\",\"name\":\"Drive\"},{\"key\":\"cb_dist_type\",\"name\":\"Distor"
    "tion\"},{\"key\":\"cb_level\",\"name\":\"Level\"}]},\"ch\":{\"name\":\"Closed Hat\",\"knobs\":[\"ch_tune\",\"ch_decay\",\""
    "ch_drive\",\"ch_dist_type\",\"ch_level\",\"hh_choke\"],\"params\":[{\"key\":\"ch_tune\",\"name\":\"Tune\"},{\"key\":\"ch"
    "_decay\",\"name\":\"Decay\"},{\"key\":\"ch_drive\",\"name\":\"Drive\"},{\"key\":\"ch_dist_type\",\"name\":\"Distortion\"}"
    ",{\"key\":\"ch_level\",\"name\":\"Level\"},{\"key\":\"hh_choke\",\"name\":\"Choke\"}]},\"oh\":{\"name\":\"Open Hat\",\"knob"
    "s\":[\"oh_tune\",\"oh_decay\",\"oh_drive\",\"oh_dist_type\",\"oh_level\"],\"params\":[{\"key\":\"oh_tune\",\"name\":\"Tu"
    "ne\"},{\"key\":\"oh_decay\",\"name\":\"Decay\"},{\"key\":\"oh_drive\",\"name\":\"Drive\"},{\"key\":\"oh_dist_type\",\"name"
    "\":\"Distortion\"},{\"key\":\"oh_level\",\"name\":\"Level\"}]},\"cy\":{\"name\":\"Cymbal\",\"knobs\":[\"cy_tune\",\"cy_dec"
    "ay\",\"cy_drive\",\"cy_dist_type\",\"cy_level\"],\"params\":[{\"key\":\"cy_tune\",\"name\":\"Tune\"},{\"key\":\"cy_decay"
    "\",\"name\":\"Decay\"},{\"key\":\"cy_drive\",\"name\":\"Drive\"},{\"key\":\"cy_dist_type\",\"name\":\"Distortion\"},{\"key"
    "\":\"cy_level\",\"name\":\"Level\"}]},\"root\":{\"name\":\"8W8\",\"knobs\":[\"master_dist\",\"master_drive\",\"volume\",\""
    "accent\"],\"params\":[{\"level\":\"bd\",\"label\":\"Bass Drum\"},{\"level\":\"sd\",\"label\":\"Snare\"},{\"level\":\"lt\",\""
    "label\":\"Low Tom\"},{\"level\":\"mt\",\"label\":\"Mid Tom\"},{\"level\":\"ht\",\"label\":\"Hi Tom\"},{\"level\":\"lc\",\"la"
    "bel\":\"Low Conga\"},{\"level\":\"mc\",\"label\":\"Mid Conga\"},{\"level\":\"hc\",\"label\":\"Hi Conga\"},{\"level\":\"rs\""
    ",\"label\":\"Rim Shot\"},{\"level\":\"cl\",\"label\":\"Claves\"},{\"level\":\"ma\",\"label\":\"Maracas\"},{\"level\":\"cp\","
    "\"label\":\"Hand Clap\"},{\"level\":\"cb\",\"label\":\"Cowbell\"},{\"level\":\"ch\",\"label\":\"Closed Hat\"},{\"level\":\""
    "oh\",\"label\":\"Open Hat\"},{\"level\":\"cy\",\"label\":\"Cymbal\"},{\"key\":\"master_dist\",\"name\":\"Master Dist\"},{"
    "\"key\":\"master_drive\",\"name\":\"Master Drive\"},{\"key\":\"volume\",\"name\":\"Volume\"},{\"key\":\"accent\",\"name\":"
    "\"Accent\"},{\"key\":\"hh_choke\",\"name\":\"Choke\"},{\"key\":\"note_map\",\"name\":\"Note Map\"}]}}}";

#endif /* SC808_PARAMS_H */
