/*
 * golden_check.cpp — the kit's sound, frozen as numbers.
 *
 * WHY THIS EXISTS. The voices were tuned one at a time against the player's
 * own reference renders, over many rounds, and each one was signed off by
 * ear on the hardware. That work is not reproducible from the source: it
 * lives in filter corners and envelope constants that nothing else asserts.
 * Structural work — deleting the Engine switches, adding sends, replacing
 * accent with velocity — touches the engine that WRAPS those voices, and a
 * mistake there is silent: the kit still plays, it just plays something
 * else.
 *
 * So: render every lane on its own through the real engine, at the panel's
 * defaults, and record a checksum plus a few coarse descriptors. Run it
 * before a structural change to write the baseline, run it after to prove
 * the audio did not move.
 *
 *   ./build-native/golden_check --write   > tools/golden.txt   (baseline)
 *   ./build-native/golden_check           compares against tools/golden.txt
 *
 * The descriptors are there so a FAILURE is readable: a bare hash says
 * "something changed", peak/rms/centroid/length say what.
 *
 * This asserts NOTHING about whether the kit sounds good — that is the
 * player's ear and it has already ruled. It asserts only that today's build
 * makes the same samples yesterday's did.
 *
 * GPL-3.0.
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sc808_engine.h"

static const double SR = 44100.0;
static const int    kTailFrames = (int)(SR * 3.0);   /* longest voice + slack */

/* FNV-1a over the raw sample bits. Exact: a one-LSB drift is a failure, and
 * it should be — nothing in a structural refactor has any business changing
 * a sample value at all. */
static unsigned long long hash_samples(const float *v, int n)
{
    unsigned long long h = 1469598103934665603ULL;
    for(int i = 0; i < n; ++i)
    {
        unsigned int b;
        memcpy(&b, &v[i], sizeof b);
        if(v[i] == 0.0f) b = 0;             /* -0.0 and +0.0 are one value */
        for(int k = 0; k < 4; ++k)
        {
            h ^= (unsigned char)(b >> (k * 8));
            h *= 1099511628211ULL;
        }
    }
    return h;
}

struct Desc {
    unsigned long long hash;
    double peak, rms, centroid, len;
};

/* One lane, one hit, at the panel defaults. Velocity 100 is the accented
 * value the engine's own threshold uses, so this exercises the accent path
 * too. */
static Desc render_voice(int v, int velocity)
{
    sc808_engine_t *e = sc808_create((float)SR);
    static float buf[3 * 44100 + 64];
    memset(buf, 0, sizeof buf);

    sc808_trigger(e, v, velocity);
    sc808_render(e, buf, kTailFrames);

    Desc d;
    d.hash = hash_samples(buf, kTailFrames);
    d.peak = 0.0; double sum = 0.0;
    int last = 0;
    for(int i = 0; i < kTailFrames; ++i)
    {
        const double x = fabs((double)buf[i]);
        if(x > d.peak) d.peak = x;
        sum += (double)buf[i] * (double)buf[i];
        if(x > 3.2e-5) last = i;
    }
    d.rms = sqrt(sum / kTailFrames);
    d.len = (double)last / SR;

    /* Spectral centroid over a log bank — coarse on purpose: it is a
     * readability aid for a failing line, not a measurement. */
    double num = 0.0, den = 0.0;
    for(double f = 60.0; f < 16000.0; f *= 1.10)
    {
        const double w = 2.0 * M_PI * f / SR;
        const double cw = 2.0 * cos(w);
        double s1 = 0.0, s2 = 0.0;
        for(int i = 0; i < kTailFrames; ++i)
        {
            const double s0 = (double)buf[i] + cw * s1 - s2;
            s2 = s1; s1 = s0;
        }
        double m = s1 * s1 + s2 * s2 - cw * s1 * s2;
        if(m < 0.0) m = 0.0;
        num += f * m; den += m;
    }
    d.centroid = den > 0.0 ? num / den : 0.0;

    sc808_destroy(e);
    return d;
}

int main(int argc, char **argv)
{
    const bool write = argc > 1 && !strcmp(argv[1], "--write");

    /* Two velocities: one under the accent threshold, one over it. Whatever
     * replaces accent has to keep both ends honest. */
    static const int kVels[2] = { 64, 110 };

    if(write)
    {
        printf("# 8W8 golden render — generated by tools/golden_check --write\n");
        printf("# lane vel hash peak rms centroid length\n");
        for(int v = 0; v < SC808_NUM_VOICES; ++v)
            for(int k = 0; k < 2; ++k)
            {
                const Desc d = render_voice(v, kVels[k]);
                printf("%s %d %llu %.9f %.9f %.3f %.6f\n",
                       sc808_voice_id(v), kVels[k], d.hash,
                       d.peak, d.rms, d.centroid, d.len);
            }
        return 0;
    }

    FILE *f = fopen("tools/golden.txt", "r");
    if(!f)
    {
        printf("FAIL: tools/golden.txt missing — run --write to make a baseline\n");
        return 1;
    }
    char line[512];
    int fails = 0, checked = 0;
    while(fgets(line, sizeof line, f))
    {
        if(line[0] == '#' || line[0] == '\n') continue;
        char id[32]; int vel; unsigned long long h;
        double peak, rms, cen, len;
        if(sscanf(line, "%31s %d %llu %lf %lf %lf %lf",
                  id, &vel, &h, &peak, &rms, &cen, &len) != 7) continue;

        int v = -1;
        for(int i = 0; i < SC808_NUM_VOICES; ++i)
            if(!strcmp(sc808_voice_id(i), id)) { v = i; break; }
        if(v < 0)
        {
            printf("FAIL: %s — lane no longer exists\n", id);
            ++fails; continue;
        }
        const Desc d = render_voice(v, vel);
        ++checked;
        if(d.hash == h) continue;

        ++fails;
        printf("FAIL: %s vel %d — audio changed\n", id, vel);
        printf("      peak     %.6f -> %.6f  (%+.2f dB)\n", peak, d.peak,
               peak > 0 && d.peak > 0 ? 20.0 * log10(d.peak / peak) : 0.0);
        printf("      rms      %.6f -> %.6f  (%+.2f dB)\n", rms, d.rms,
               rms > 0 && d.rms > 0 ? 20.0 * log10(d.rms / rms) : 0.0);
        printf("      centroid %.0f Hz -> %.0f Hz\n", cen, d.centroid);
        printf("      length   %.3f s -> %.3f s\n", len, d.len);
    }
    fclose(f);

    if(fails)
        printf("\nFAILED (%d of %d lane/velocity renders moved)\n", fails, checked);
    else
        printf("ALL PASS (%d lane/velocity renders bit-identical)\n", checked);
    return fails ? 1 : 0;
}
